server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: false

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: ${AUTH_SERVICE_URL:http://localhost:55002/ms-auth/}
          predicates:
            - Path=/auth/**
  sleuth:
    enabled: true
    sampler:
      probability: 1

logging:
  file:
    name: ${LOG_URL:./ms-proxy.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%-5level][%t][%X{traceId}|%X{spanId}][%X{tid}][%c{1.}] %msg%n"
    level: ${LOG_LEVEL:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    header: Authorization
    prefix: Bearer
    key: ${SIGN_KEY:7R9SATCVDWEXGZH2J4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7Q8SATBUCWEXFY}